name: DonorTitles
author:
  - Favorlock
main: com.favorlock.donortitles.DonorTitles
version: 0.3.5b
depend: [Vault]
commands:
  title:
    description: DonorTitles commands
    usage: /<command>