name: DonorTitles
author:
  - Favorlock
main: com.favorlock.donortitles.DonorTitles
version: 0.3.2
depend: [Vault]
commands:
  titles:
    description: DonorTitles commands
    usage: /<command>